// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu2ge8TrZt_tc-gw3-vLQ1jne9g2R9SmI',
    appId: '1:176707051228:web:9f66e265a3bbd090fa9e19',
    messagingSenderId: '176707051228',
    projectId: 'hostel-owner',
    authDomain: 'hostel-owner.firebaseapp.com',
    storageBucket: 'hostel-owner.appspot.com',
    measurementId: 'G-6YNSF2JQL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo_LAIh83MWgPCvBc_U9ln5wgaDILSs_A',
    appId: '1:176707051228:android:20d43884b2b85e14fa9e19',
    messagingSenderId: '176707051228',
    projectId: 'hostel-owner',
    storageBucket: 'hostel-owner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpwCc3wunjegEKj3d6Y9g5rYUNdPX4-cw',
    appId: '1:176707051228:ios:96147a0f215088c1fa9e19',
    messagingSenderId: '176707051228',
    projectId: 'hostel-owner',
    storageBucket: 'hostel-owner.appspot.com',
    iosBundleId: 'org.div.hostelOwner',
  );
}
